POST http://127.0.0.1:80/user/add
Content-Type: application/json

{
  "username": "Dovish",
  "password": "005135",
  "firstName": "天浩",
  "lastName": "李",
  "telephone": "13583167770"
}

###
POST http://124.71.1.201:80/user/add
Content-Type: application/json

{
  "username": "Future",
  "password": "005135",
  "firstName": "晓瑞",
  "lastName": "吴",
  "telephone": "13583167770"
}
